pipeline {
    agent { label 'kubepods' }
    stages {
        stage('first') {
            input {
                message "Testing input"
                ok "Lets Proceed"
                parameters {
                    string(name: 'user', defaultValue: 'PrudviBilakanti', description: 'input testing')
                }
            }
            steps{
                echo 'Hello ${user}'
            }
            
        }
    }
}

